services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=luis.r@clubcashin.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    container_name: cci-reverse-proxy

  backend:
    image: 445567109675.dkr.ecr.us-east-1.amazonaws.com/cci/backend:7f87c4a32135f5e471ce247120b65c5d6277e48b124f425cd333d24f8d0e3691
    container_name: cci-backend
    env_file:
      - secrets/backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.server.devteamatcci.site`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
  landing-page:
    image: 445567109675.dkr.ecr.us-east-1.amazonaws.com/cci/landing:6d8f10e7cd49193716de53333799712b864811d9c90aac9e5ff12bc6ecc28330
    container_name: cci-landing
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing-page.rule=Host(`landing.server.devteamatcci.site`)"
      - "traefik.http.routers.landing-page.entrypoints=websecure"
      - "traefik.http.routers.landing-page.tls.certresolver=myresolver"

  investment-calculator:
    image: 445567109675.dkr.ecr.us-east-1.amazonaws.com/cci/investment-calculator:latest
    container_name: cci-investment-calculator
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.investment-calculator.rule=Host(`investment.server.devteamatcci.site`)"
      - "traefik.http.routers.investment-calculator.entrypoints=websecure"
      - "traefik.http.routers.investment-calculator.tls.certresolver=myresolver"

volumes:
  letsencrypt:
