services:
  backend:
    image: 445567109675.dkr.ecr.us-east-1.amazonaws.com/cci/backend:latest
    container_name: cci-backend
    ports:
      - 9000:9000
    secrets:
      - cci-backend-env

  landing-page:
    image: 445567109675.dkr.ecr.us-east-1.amazonaws.com/cci/landing:latest
    container_name: cci-landing
    ports:
      - 4321:4321

  investment-calculator:
    image: 445567109675.dkr.ecr.us-east-1.amazonaws.com/cci/investment-calculator:latest
    container_name: cci-investment-calculator
    ports:
      - 80:80

secrets:
  cci-backend-env:
    file: secrets/backend.env
