[project]
name = "cci-mcp-server"
version = "0.1.0"
description = "Example MCP server"
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.30.0",
    "fastmcp==2.6.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]
