/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationsRouteImport } from './routes/presentations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GoalsReportsRouteImport } from './routes/goals/reports'
import { Route as GoalsMyGoalsRouteImport } from './routes/goals/my-goals'
import { Route as GoalsConfigureRouteImport } from './routes/goals/configure'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as AdminGoalTemplatesRouteImport } from './routes/admin/goal-templates'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminAreasRouteImport } from './routes/admin/areas'
import { Route as PresentationsIdViewRouteImport } from './routes/presentations/$id.view'
import { Route as PresentationsIdSubmitRouteImport } from './routes/presentations/$id.submit'

const PresentationsRoute = PresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PresentationsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const GoalsReportsRoute = GoalsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => GoalsRoute,
} as any)
const GoalsMyGoalsRoute = GoalsMyGoalsRouteImport.update({
  id: '/my-goals',
  path: '/my-goals',
  getParentRoute: () => GoalsRoute,
} as any)
const GoalsConfigureRoute = GoalsConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => GoalsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoalTemplatesRoute = AdminGoalTemplatesRouteImport.update({
  id: '/goal-templates',
  path: '/goal-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAreasRoute = AdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AdminRoute,
} as any)
const PresentationsIdViewRoute = PresentationsIdViewRouteImport.update({
  id: '/$id/view',
  path: '/$id/view',
  getParentRoute: () => PresentationsRoute,
} as any)
const PresentationsIdSubmitRoute = PresentationsIdSubmitRouteImport.update({
  id: '/$id/submit',
  path: '/$id/submit',
  getParentRoute: () => PresentationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRouteWithChildren
  '/login': typeof LoginRoute
  '/presentations': typeof PresentationsRouteWithChildren
  '/admin/areas': typeof AdminAreasRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/goal-templates': typeof AdminGoalTemplatesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/goals/configure': typeof GoalsConfigureRoute
  '/goals/my-goals': typeof GoalsMyGoalsRoute
  '/goals/reports': typeof GoalsReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/presentations/$id/submit': typeof PresentationsIdSubmitRoute
  '/presentations/$id/view': typeof PresentationsIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/goal-templates': typeof AdminGoalTemplatesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/goals/configure': typeof GoalsConfigureRoute
  '/goals/my-goals': typeof GoalsMyGoalsRoute
  '/goals/reports': typeof GoalsReportsRoute
  '/admin': typeof AdminIndexRoute
  '/presentations': typeof PresentationsIndexRoute
  '/presentations/$id/submit': typeof PresentationsIdSubmitRoute
  '/presentations/$id/view': typeof PresentationsIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRouteWithChildren
  '/login': typeof LoginRoute
  '/presentations': typeof PresentationsRouteWithChildren
  '/admin/areas': typeof AdminAreasRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/goal-templates': typeof AdminGoalTemplatesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/goals/configure': typeof GoalsConfigureRoute
  '/goals/my-goals': typeof GoalsMyGoalsRoute
  '/goals/reports': typeof GoalsReportsRoute
  '/admin/': typeof AdminIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/presentations/$id/submit': typeof PresentationsIdSubmitRoute
  '/presentations/$id/view': typeof PresentationsIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/goals'
    | '/login'
    | '/presentations'
    | '/admin/areas'
    | '/admin/departments'
    | '/admin/goal-templates'
    | '/admin/teams'
    | '/admin/users'
    | '/goals/configure'
    | '/goals/my-goals'
    | '/goals/reports'
    | '/admin/'
    | '/presentations/'
    | '/presentations/$id/submit'
    | '/presentations/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/goals'
    | '/login'
    | '/admin/areas'
    | '/admin/departments'
    | '/admin/goal-templates'
    | '/admin/teams'
    | '/admin/users'
    | '/goals/configure'
    | '/goals/my-goals'
    | '/goals/reports'
    | '/admin'
    | '/presentations'
    | '/presentations/$id/submit'
    | '/presentations/$id/view'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/goals'
    | '/login'
    | '/presentations'
    | '/admin/areas'
    | '/admin/departments'
    | '/admin/goal-templates'
    | '/admin/teams'
    | '/admin/users'
    | '/goals/configure'
    | '/goals/my-goals'
    | '/goals/reports'
    | '/admin/'
    | '/presentations/'
    | '/presentations/$id/submit'
    | '/presentations/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  GoalsRoute: typeof GoalsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PresentationsRoute: typeof PresentationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof PresentationsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/goals/reports': {
      id: '/goals/reports'
      path: '/reports'
      fullPath: '/goals/reports'
      preLoaderRoute: typeof GoalsReportsRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/goals/my-goals': {
      id: '/goals/my-goals'
      path: '/my-goals'
      fullPath: '/goals/my-goals'
      preLoaderRoute: typeof GoalsMyGoalsRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/goals/configure': {
      id: '/goals/configure'
      path: '/configure'
      fullPath: '/goals/configure'
      preLoaderRoute: typeof GoalsConfigureRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/goal-templates': {
      id: '/admin/goal-templates'
      path: '/goal-templates'
      fullPath: '/admin/goal-templates'
      preLoaderRoute: typeof AdminGoalTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/areas': {
      id: '/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AdminAreasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/presentations/$id/view': {
      id: '/presentations/$id/view'
      path: '/$id/view'
      fullPath: '/presentations/$id/view'
      preLoaderRoute: typeof PresentationsIdViewRouteImport
      parentRoute: typeof PresentationsRoute
    }
    '/presentations/$id/submit': {
      id: '/presentations/$id/submit'
      path: '/$id/submit'
      fullPath: '/presentations/$id/submit'
      preLoaderRoute: typeof PresentationsIdSubmitRouteImport
      parentRoute: typeof PresentationsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAreasRoute: typeof AdminAreasRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminGoalTemplatesRoute: typeof AdminGoalTemplatesRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAreasRoute: AdminAreasRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminGoalTemplatesRoute: AdminGoalTemplatesRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GoalsRouteChildren {
  GoalsConfigureRoute: typeof GoalsConfigureRoute
  GoalsMyGoalsRoute: typeof GoalsMyGoalsRoute
  GoalsReportsRoute: typeof GoalsReportsRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsConfigureRoute: GoalsConfigureRoute,
  GoalsMyGoalsRoute: GoalsMyGoalsRoute,
  GoalsReportsRoute: GoalsReportsRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

interface PresentationsRouteChildren {
  PresentationsIndexRoute: typeof PresentationsIndexRoute
  PresentationsIdSubmitRoute: typeof PresentationsIdSubmitRoute
  PresentationsIdViewRoute: typeof PresentationsIdViewRoute
}

const PresentationsRouteChildren: PresentationsRouteChildren = {
  PresentationsIndexRoute: PresentationsIndexRoute,
  PresentationsIdSubmitRoute: PresentationsIdSubmitRoute,
  PresentationsIdViewRoute: PresentationsIdViewRoute,
}

const PresentationsRouteWithChildren = PresentationsRoute._addFileChildren(
  PresentationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  GoalsRoute: GoalsRouteWithChildren,
  LoginRoute: LoginRoute,
  PresentationsRoute: PresentationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
