export * from './IconLeftArrow';
export * from './IconRightArrow';
export * from './IconX';
export * from "./IconGoogle"
export * from "./IconCheck"
export * from "./IconPlay"
export * from "./color"
export * from "./IconUser"
export * from "./IconAddUser"
export * from "./IconQ"
export * from "./IconWallet"
export * from "./IconArrowsSelect"
export * from "./IconCalculator"
export * from "./IconAddress"
export * from "./IconPhone"
export * from "./IconPerson"
export * from "./IconDocument"
export * from "./IconOut"
export * from "./IconGraph"