export * from './IconLeftArrow';
export * from './IconRightArrow';
export * from './IconX';
export * from "./IconGoogle"
export * from "./IconCheck"
export * from "./IconPlay"
export * from "./color"
export * from "./IconUser"
export * from "./IconAddUser"
export * from "./IconQ"
export * from "./IconWallet"
export * from "./IconArrowsSelect"
export * from "./IconCalculator"