export * from './IconLeftArrow';
export * from './IconRightArrow';
export * from './IconX';
export * from "./IconGoogle"
export * from "./IconCheck"
export * from "./IconPlay"
export * from "./color"
export * from "./IconUser"
export * from "./IconAddUser"
export * from "./IconQ"
export * from "./IconWallet"
export * from "./IconArrowsSelect"
export * from "./IconCalculator"
export * from "./IconAddress"
export * from "./IconPhone"
export * from "./IconPerson"
export * from "./IconDocument"
export * from "./IconOut"
export * from "./IconGraph"
export * from "./IconCalendarSmall";
export * from "./IconGear";
export * from "./IconDownload"
export * from "./IconTarget"
export * from "./IconPlus"

export * from "./IconGas"   
export * from "./IconKms"   
export * from "./IconPrint" 
export * from "./IconLike"
export * from "./IconShare"
export * from "./IconCall"
export * from "./IconWhatsApp"
export * from "./IconReport"